version: '3'
services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: school
      MYSQL_PASSWORD: admin
      MYSQL_USER: sa
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    networks:
      - springapimysql-net
    volumes:
      - /path/on/host:/var/lib/mysql


networks:
  springapimysql-net:
